import { useEffect, useState, useCallback } from 'react'
import { Plus, X, ShoppingCart, CheckCircle, XCircle, Truck, Pencil, Trash2, FileText, Mail, History } from 'lucide-react'
import { format } from 'date-fns'

const emptyItem = { productId: '', productName: '', productCode: '', quantity: 1, unitPrice: 0, taxRate: 18, taxAmount: 0, total: 0, receivedQty: 0 }

const STATUS_STYLES = {
  draft: 'bg-gray-100 text-gray-600',
  sent: 'bg-blue-100 text-blue-700',
  partial: 'bg-yellow-100 text-yellow-700',
  received: 'bg-green-100 text-green-700',
  cancelled: 'bg-red-100 text-red-700',
}

function getToken() { return typeof window !== 'undefined' ? localStorage.getItem('token') || '' : '' }

async function fetchCompanyInfo() {
  const res = await fetch('/api/companies/me', { headers: { Authorization: `Bearer ${getToken()}` } })
  const json = await res.json()
  return json.success ? json.data.company : null
}

function generatePOPdf(po, company) {
  return import('jspdf').then(({ jsPDF }) => {
    return import('jspdf-autotable').then(() => {
      const doc = new jsPDF({ unit: 'mm', format: 'a4' })
      const pageW = doc.internal.pageSize.getWidth()

      doc.setFillColor(15, 23, 42)
      doc.rect(0, 0, pageW, 28, 'F')
      doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
      doc.text('PURCHASE ORDER', 14, 12)
      doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(148, 163, 184)
      doc.text(company.name || '', 14, 19)
      doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
      doc.text(po.poNumber, pageW - 14, 12, { align: 'right' })
      doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(148, 163, 184)
      doc.text(`Status: ${po.status.toUpperCase()}`, pageW - 14, 19, { align: 'right' })
      doc.text(`Date: ${format(new Date(po.createdAt), 'dd MMM yyyy')}`, pageW - 14, 24, { align: 'right' })

      let y = 36
      doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(100, 116, 139)
      doc.text('FROM (BUYER)', 14, y)
      doc.text('TO (SUPPLIER)', pageW / 2, y)
      y += 5
      doc.setFont('helvetica', 'bold'); doc.setTextColor(15, 23, 42); doc.setFontSize(9)
      doc.text(company.name || '', 14, y)
      doc.text(po.supplierName, pageW / 2, y)
      y += 4; doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(71, 85, 105)
      if (company.address) doc.text(company.address, 14, y)
      y += 4
      if (company.phone) { doc.text(`Ph: ${company.phone}`, 14, y) }
      if (company.gstNumber) { doc.text(`GST: ${company.gstNumber}`, 14, y + 4) }

      if (po.expectedDelivery) {
        y += 10
        doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(100, 116, 139)
        doc.text(`Expected Delivery: `, 14, y)
        doc.setFont('helvetica', 'normal'); doc.setTextColor(15, 23, 42)
        doc.text(format(new Date(po.expectedDelivery), 'dd MMM yyyy'), 50, y)
      }

      y += 10
      const tableData = po.items.map((item, i) => [
        String(i + 1),
        item.productName + (item.productCode ? `\n${item.productCode}` : ''),
        String(item.quantity),
        `₹${item.unitPrice.toFixed(2)}`,
        `${item.taxRate || 0}%`,
        `₹${item.total.toFixed(2)}`,
      ])
      doc.autoTable({
        startY: y,
        head: [['#', 'Product / Description', 'Qty', 'Unit Price', 'Tax', 'Amount']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 8 },
        bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
        columnStyles: { 0: { cellWidth: 10 }, 2: { halign: 'center' }, 3: { halign: 'right' }, 4: { halign: 'center' }, 5: { halign: 'right' } },
        margin: { left: 14, right: 14 },
      })

      const afterTable = doc.lastAutoTable.finalY + 6
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(100, 116, 139)
      doc.text(`Subtotal: ₹${(po.subtotal || 0).toFixed(2)}`, pageW - 14, afterTable, { align: 'right' })
      doc.text(`Tax: ₹${(po.taxTotal || 0).toFixed(2)}`, pageW - 14, afterTable + 5, { align: 'right' })
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(15, 23, 42)
      doc.text(`Grand Total: ₹${po.grandTotal.toLocaleString('en-IN')}`, pageW - 14, afterTable + 12, { align: 'right' })

      if (po.notes) {
        doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(100, 116, 139)
        doc.text(`Notes: ${po.notes}`, 14, afterTable + 6)
      }

      const footerY = doc.internal.pageSize.getHeight() - 12
      doc.setFillColor(15, 23, 42); doc.rect(0, footerY, pageW, 12, 'F')
      doc.setFontSize(7); doc.setTextColor(200, 215, 255)
      doc.text('Generated by SmartBilling  •  This is a computer-generated document.', pageW / 2, footerY + 7, { align: 'center' })

      return doc
    })
  })
}

export default function PurchaseOrdersPage() {
  const [pos, setPos] = useState([])
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [editingPO, setEditingPO] = useState(null)
  const [submitting, setSubmitting] = useState(false)
  const [formError, setFormError] = useState('')
  const [suppliers, setSuppliers] = useState([])
  const [products, setProducts] = useState([])
  const [expandedId, setExpandedId] = useState(null)
  const [company, setCompany] = useState(null)

  const [emailModal, setEmailModal] = useState({ open: false, po: null })
  const [emailTab, setEmailTab] = useState('compose')
  const [emailTo, setEmailTo] = useState('')
  const [emailCc, setEmailCc] = useState('')
  const [emailBcc, setEmailBcc] = useState('')
  const [emailSubject, setEmailSubject] = useState('')
  const [emailMessage, setEmailMessage] = useState('')
  const [sendingEmail, setSendingEmail] = useState(false)
  const [emailMsg, setEmailMsg] = useState(null)
  const [emailHistory, setEmailHistory] = useState([])
  const [historyLoading, setHistoryLoading] = useState(false)

  const [form, setForm] = useState({
    supplierId: '', expectedDelivery: '', notes: '',
    items: [{ ...emptyItem }],
  })

  const fetchPOs = useCallback(async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/purchase-orders', { headers: { Authorization: `Bearer ${getToken()}` } })
      const json = await res.json()
      if (json.success) setPos(json.data.purchaseOrders)
    } finally { setLoading(false) }
  }, [])

  useEffect(() => {
    fetchPOs()
    fetchCompanyInfo().then(setCompany)
  }, [fetchPOs])

  async function loadFormData() {
    const [sRes, pRes] = await Promise.all([
      fetch('/api/suppliers', { headers: { Authorization: `Bearer ${getToken()}` } }),
      fetch('/api/products?status=approved&limit=500', { headers: { Authorization: `Bearer ${getToken()}` } }),
    ])
    const [sJson, pJson] = await Promise.all([sRes.json(), pRes.json()])
    if (sJson.success) setSuppliers(sJson.data.suppliers)
    if (pJson.success) setProducts(pJson.data.products)
  }

  async function openCreateForm() {
    setEditingPO(null)
    setForm({ supplierId: '', expectedDelivery: '', notes: '', items: [{ ...emptyItem }] })
    setFormError('')
    await loadFormData()
    setShowForm(true)
  }

  async function openEditForm(po) {
    setEditingPO(po)
    setForm({
      supplierId: po.supplierId || '',
      expectedDelivery: po.expectedDelivery ? format(new Date(po.expectedDelivery), 'yyyy-MM-dd') : '',
      notes: po.notes || '',
      items: po.items.map((item) => ({ ...item, productId: item.productId || '' })),
    })
    setFormError('')
    await loadFormData()
    setShowForm(true)
  }

  function updateItem(i, field, value) {
    const items = [...form.items]
    const item = { ...items[i], [field]: value }
    if (field === 'productId') {
      const product = products.find((p) => p._id === value)
      if (product) {
        item.productName = product.name
        item.productCode = product.code
        item.unitPrice = product.basePrice
        item.taxRate = product.taxRate
      }
    }
    const lineTotal = Number(item.quantity) * Number(item.unitPrice)
    item.taxAmount = (lineTotal * Number(item.taxRate)) / 100
    item.total = lineTotal + item.taxAmount
    items[i] = item
    setForm({ ...form, items })
  }

  async function handleSubmit(e) {
    e.preventDefault()
    setSubmitting(true)
    setFormError('')
    const supplier = suppliers.find((s) => s._id === form.supplierId)
    try {
      let res
      if (editingPO) {
        res = await fetch(`/api/purchase-orders/${editingPO._id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` },
          body: JSON.stringify({
            supplierId: form.supplierId,
            supplierName: supplier?.name,
            notes: form.notes,
            expectedDelivery: form.expectedDelivery || undefined,
            items: form.items,
          }),
        })
      } else {
        res = await fetch('/api/purchase-orders', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` },
          body: JSON.stringify({ ...form, supplierName: supplier?.name, expectedDelivery: form.expectedDelivery || undefined }),
        })
      }
      const json = await res.json()
      if (json.success) { setShowForm(false); setEditingPO(null); fetchPOs() }
      else setFormError(json.message)
    } finally { setSubmitting(false) }
  }

  async function handleStatusChange(id, status) {
    if (!confirm(`Change status to "${status}"?`)) return
    const res = await fetch(`/api/purchase-orders/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` },
      body: JSON.stringify({ status }),
    })
    const json = await res.json()
    if (json.success) fetchPOs()
    else alert(json.message)
  }

  async function handleDelete(id) {
    if (!confirm('Delete this purchase order? This action cannot be undone.')) return
    const res = await fetch(`/api/purchase-orders/${id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${getToken()}` },
    })
    const json = await res.json()
    if (json.success) fetchPOs()
    else alert(json.message)
  }

  async function handleDownloadPDF(po) {
    try {
      const info = company || await fetchCompanyInfo()
      const doc = await generatePOPdf(po, info || { name: '' })
      doc.save(`${po.poNumber}.pdf`)
    } catch {
      alert('Failed to generate PDF')
    }
  }

  function openEmailModal(po) {
    setEmailModal({ open: true, po })
    setEmailTab('compose')
    setEmailTo('')
    setEmailCc('')
    setEmailBcc('')
    setEmailSubject(`Purchase Order ${po.poNumber} from ${company?.name || ''}`)
    setEmailMessage(`Dear ${po.supplierName},\n\nPlease find attached our Purchase Order ${po.poNumber} for ₹${po.grandTotal.toLocaleString('en-IN')}.\n\nKindly confirm receipt and expected delivery date.\n\nThank you.`)
    setEmailMsg(null)
    setEmailHistory([])
  }

  async function fetchEmailHistory(poNumber) {
    setHistoryLoading(true)
    try {
      const res = await fetch(`/api/emails?documentType=purchase-order&search=${poNumber}`, {
        headers: { Authorization: `Bearer ${getToken()}` },
      })
      const json = await res.json()
      if (json.success) setEmailHistory(json.data.logs)
    } finally { setHistoryLoading(false) }
  }

  async function handleSendEmail() {
    if (!emailModal.po) return
    const toList = emailTo.split(',').map((e) => e.trim()).filter((e) => e.includes('@'))
    const ccList = emailCc.split(',').map((e) => e.trim()).filter((e) => e.includes('@'))
    const bccList = emailBcc.split(',').map((e) => e.trim()).filter((e) => e.includes('@'))
    if (toList.length === 0) { setEmailMsg({ type: 'error', text: 'Please enter at least one valid To email' }); return }
    setSendingEmail(true); setEmailMsg(null)
    try {
      const info = company || await fetchCompanyInfo()
      const doc = await generatePOPdf(emailModal.po, info || { name: '' })
      const pdfBase64 = doc.output('datauristring').split(',')[1]
      const res = await fetch(`/api/purchase-orders/${emailModal.po._id}/email`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` },
        body: JSON.stringify({ emails: toList, cc: ccList, bcc: bccList, subject: emailSubject, message: emailMessage, pdfBase64 }),
      })
      const json = await res.json()
      setEmailMsg({ type: json.success ? 'success' : 'error', text: json.message })
    } catch {
      setEmailMsg({ type: 'error', text: 'Failed to send email' })
    } finally { setSendingEmail(false) }
  }

  const totals = form.items.reduce((acc, item) => ({ grand: acc.grand + item.total, tax: acc.tax + item.taxAmount }), { grand: 0, tax: 0 })

  return (
    <div>
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Purchase Orders</h1>
          <p className="text-sm text-gray-500 mt-0.5">Manage procurement from suppliers</p>
        </div>
        <button onClick={openCreateForm}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition shadow-sm">
          <Plus className="w-4 h-4" /> New PO
        </button>
      </div>

      {/* Create / Edit Form */}
      {showForm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-5 border-b sticky top-0 bg-white z-10">
              <h2 className="text-base font-semibold text-gray-800">
                {editingPO ? `Edit Purchase Order — ${editingPO.poNumber}` : 'Create Purchase Order'}
              </h2>
              <button onClick={() => { setShowForm(false); setEditingPO(null) }} className="text-gray-400 hover:text-gray-600">
                <X className="w-5 h-5" />
              </button>
            </div>
            {formError && <div className="mx-5 mt-4 bg-red-50 border border-red-200 text-red-700 rounded-lg px-4 py-2 text-sm">{formError}</div>}
            <form onSubmit={handleSubmit} className="p-5 space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Supplier *</label>
                  <select required value={form.supplierId} onChange={(e) => setForm({ ...form, supplierId: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
                    <option value="">Select supplier</option>
                    {suppliers.map((s) => <option key={s._id} value={s._id}>{s.name}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Expected Delivery</label>
                  <input type="date" value={form.expectedDelivery} onChange={(e) => setForm({ ...form, expectedDelivery: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Notes</label>
                  <input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-sm font-semibold text-gray-700">Items</h3>
                  <button type="button" onClick={() => setForm({ ...form, items: [...form.items, { ...emptyItem }] })}
                    className="text-xs text-blue-600 hover:text-blue-700 font-medium flex items-center gap-1">
                    <Plus className="w-3 h-3" /> Add Row
                  </button>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-gray-100">
                        <th className="text-left text-xs font-medium text-gray-500 pb-2 pr-3 min-w-[200px]">Product</th>
                        <th className="text-left text-xs font-medium text-gray-500 pb-2 pr-3 w-20">Qty</th>
                        <th className="text-left text-xs font-medium text-gray-500 pb-2 pr-3 w-28">Unit Price (₹)</th>
                        <th className="text-left text-xs font-medium text-gray-500 pb-2 pr-3 w-16">Tax %</th>
                        <th className="text-left text-xs font-medium text-gray-500 pb-2 w-24">Total</th>
                        <th className="w-8"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {form.items.map((item, i) => (
                        <tr key={i} className="border-b border-gray-50">
                          <td className="pr-3 py-2">
                            <select required value={item.productId}
                              onChange={(e) => updateItem(i, 'productId', e.target.value)}
                              className="w-full border border-gray-200 rounded px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500">
                              <option value="">Select product</option>
                              {products.map((p) => <option key={p._id} value={p._id}>{p.code} — {p.name}</option>)}
                            </select>
                            {item.productName && <p className="text-xs text-gray-400 mt-0.5 pl-1 truncate">{item.productName}</p>}
                          </td>
                          <td className="pr-3 py-2">
                            <input type="number" min="1" required value={item.quantity}
                              onChange={(e) => updateItem(i, 'quantity', Number(e.target.value))}
                              className="w-full border border-gray-200 rounded px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500" />
                          </td>
                          <td className="pr-3 py-2">
                            <input type="number" min="0" step="0.01" required value={item.unitPrice}
                              onChange={(e) => updateItem(i, 'unitPrice', Number(e.target.value))}
                              className="w-full border border-gray-200 rounded px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500" />
                          </td>
                          <td className="pr-3 py-2">
                            <input type="number" min="0" max="100" value={item.taxRate}
                              onChange={(e) => updateItem(i, 'taxRate', Number(e.target.value))}
                              className="w-full border border-gray-200 rounded px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500" />
                          </td>
                          <td className="py-2 text-gray-700 font-medium text-xs">₹{item.total.toFixed(2)}</td>
                          <td className="py-2">
                            {form.items.length > 1 && (
                              <button type="button" onClick={() => setForm({ ...form, items: form.items.filter((_, j) => j !== i) })}
                                className="text-gray-300 hover:text-red-500"><X className="w-4 h-4" /></button>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <div className="text-right mt-2 space-y-0.5">
                  <p className="text-xs text-gray-500">Tax: ₹{totals.tax.toFixed(2)}</p>
                  <p className="text-sm font-bold text-gray-800">Grand Total: ₹{totals.grand.toFixed(2)}</p>
                </div>
              </div>
              <div className="flex gap-3 pt-2 border-t border-gray-100">
                <button type="submit" disabled={submitting}
                  className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white text-sm font-medium px-5 py-2 rounded-lg transition">
                  {submitting ? 'Saving...' : editingPO ? 'Update PO' : 'Create PO'}
                </button>
                <button type="button" onClick={() => { setShowForm(false); setEditingPO(null) }}
                  className="border border-gray-200 text-gray-600 hover:bg-gray-50 text-sm font-medium px-5 py-2 rounded-lg transition">Cancel</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* List */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        {loading ? (
          <div className="flex justify-center py-16">
            <div className="animate-spin w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full" />
          </div>
        ) : pos.length === 0 ? (
          <div className="flex flex-col items-center py-16 text-gray-400">
            <ShoppingCart className="w-10 h-10 mb-3 text-gray-300" />
            <p className="text-sm">No purchase orders yet.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-100">
                  <th className="text-left px-5 py-3 text-xs font-medium text-gray-500">PO #</th>
                  <th className="text-left px-5 py-3 text-xs font-medium text-gray-500">Supplier</th>
                  <th className="text-right px-5 py-3 text-xs font-medium text-gray-500">Amount</th>
                  <th className="text-center px-5 py-3 text-xs font-medium text-gray-500">Status</th>
                  <th className="text-left px-5 py-3 text-xs font-medium text-gray-500">Expected</th>
                  <th className="text-left px-5 py-3 text-xs font-medium text-gray-500">Created</th>
                  <th className="text-center px-5 py-3 text-xs font-medium text-gray-500">Actions</th>
                </tr>
              </thead>
              <tbody>
                {pos.map((po) => (
                  <>
                    <tr key={po._id} className="border-t border-gray-50 hover:bg-gray-50/50 cursor-pointer"
                      onClick={() => setExpandedId(expandedId === po._id ? null : po._id)}>
                      <td className="px-5 py-3 font-medium text-gray-800">{po.poNumber}</td>
                      <td className="px-5 py-3 text-gray-700">{po.supplierName}</td>
                      <td className="px-5 py-3 text-right font-semibold">₹{po.grandTotal.toLocaleString('en-IN')}</td>
                      <td className="px-5 py-3 text-center">
                        <span className={`text-xs font-medium px-2.5 py-1 rounded-full capitalize ${STATUS_STYLES[po.status]}`}>{po.status}</span>
                      </td>
                      <td className="px-5 py-3 text-gray-400 text-xs">{po.expectedDelivery ? format(new Date(po.expectedDelivery), 'dd MMM yyyy') : '—'}</td>
                      <td className="px-5 py-3 text-gray-400 text-xs">{format(new Date(po.createdAt), 'dd MMM yyyy')}</td>
                      <td className="px-5 py-3 text-center" onClick={(e) => e.stopPropagation()}>
                        <div className="flex items-center justify-center gap-1 flex-wrap">
                          {po.status === 'draft' && (
                            <button onClick={() => handleStatusChange(po._id, 'sent')}
                              className="flex items-center gap-1 text-xs text-blue-600 hover:text-blue-700 px-2 py-1 hover:bg-blue-50 rounded-lg transition">
                              <Truck className="w-3 h-3" /> Send
                            </button>
                          )}
                          {(po.status === 'sent' || po.status === 'partial') && (
                            <button onClick={() => handleStatusChange(po._id, 'received')}
                              className="flex items-center gap-1 text-xs text-green-600 hover:text-green-700 px-2 py-1 hover:bg-green-50 rounded-lg transition">
                              <CheckCircle className="w-3 h-3" /> Receive
                            </button>
                          )}
                          {po.status !== 'received' && po.status !== 'cancelled' && (
                            <button onClick={() => handleStatusChange(po._id, 'cancelled')}
                              className="flex items-center gap-1 text-xs text-red-500 hover:text-red-600 px-2 py-1 hover:bg-red-50 rounded-lg transition">
                              <XCircle className="w-3 h-3" /> Cancel
                            </button>
                          )}
                          {po.status === 'draft' && (
                            <button onClick={() => openEditForm(po)}
                              className="p-1.5 text-blue-500 hover:bg-blue-50 rounded-lg transition" title="Edit">
                              <Pencil className="w-3.5 h-3.5" />
                            </button>
                          )}
                          <button onClick={() => handleDownloadPDF(po)}
                            className="p-1.5 text-gray-500 hover:bg-gray-100 rounded-lg transition" title="Download PDF">
                            <FileText className="w-3.5 h-3.5" />
                          </button>
                          <button onClick={() => openEmailModal(po)}
                            className="p-1.5 text-violet-500 hover:bg-violet-50 rounded-lg transition" title="Send Email">
                            <Mail className="w-3.5 h-3.5" />
                          </button>
                          {po.status !== 'received' && (
                            <button onClick={() => handleDelete(po._id)}
                              className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition" title="Delete">
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                    {expandedId === po._id && (
                      <tr key={`${po._id}-expand`}>
                        <td colSpan={7} className="px-8 pb-4 bg-blue-50/30">
                          <table className="w-full text-xs mt-2">
                            <thead>
                              <tr className="text-gray-500">
                                <th className="text-left pb-1">Item</th>
                                <th className="text-right pb-1">Ordered</th>
                                <th className="text-right pb-1">Received</th>
                                <th className="text-right pb-1">Unit Price</th>
                                <th className="text-right pb-1">Total</th>
                              </tr>
                            </thead>
                            <tbody>
                              {po.items.map((item, i) => (
                                <tr key={i} className="border-t border-blue-100">
                                  <td className="py-1 text-gray-700">{item.productName}</td>
                                  <td className="py-1 text-right text-gray-600">{item.quantity}</td>
                                  <td className={`py-1 text-right font-medium ${item.receivedQty >= item.quantity ? 'text-green-600' : item.receivedQty > 0 ? 'text-yellow-600' : 'text-gray-400'}`}>
                                    {item.receivedQty}
                                  </td>
                                  <td className="py-1 text-right text-gray-600">₹{item.unitPrice.toLocaleString()}</td>
                                  <td className="py-1 text-right font-medium text-gray-800">₹{item.total.toFixed(2)}</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                          {po.notes && <p className="text-xs text-gray-400 mt-2">Notes: {po.notes}</p>}
                        </td>
                      </tr>
                    )}
                  </>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Email Modal */}
      {emailModal.open && emailModal.po && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden">
            <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
              <div>
                <h3 className="font-semibold text-gray-800">Send Purchase Order</h3>
                <p className="text-xs text-gray-400 mt-0.5">{emailModal.po.poNumber} — {emailModal.po.supplierName}</p>
              </div>
              <button onClick={() => setEmailModal({ open: false, po: null })} className="text-gray-400 hover:text-gray-600 p-1.5 hover:bg-gray-100 rounded-lg">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="flex border-b border-gray-100">
              {['compose', 'history'].map((tab) => (
                <button key={tab} onClick={() => { setEmailTab(tab); if (tab === 'history' && emailModal.po) fetchEmailHistory(emailModal.po.poNumber) }}
                  className={`flex-1 py-2.5 text-sm font-medium capitalize flex items-center justify-center gap-1.5 transition ${emailTab === tab ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700'}`}>
                  {tab === 'history' && <History className="w-3.5 h-3.5" />} {tab}
                </button>
              ))}
            </div>

            {emailTab === 'compose' ? (
              <div className="p-6 space-y-3">
                {emailMsg && (
                  <div className={`px-4 py-2.5 rounded-lg text-sm ${emailMsg.type === 'success' ? 'bg-green-50 border border-green-200 text-green-700' : 'bg-red-50 border border-red-200 text-red-700'}`}>
                    {emailMsg.text}
                  </div>
                )}
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">To * <span className="text-gray-400 font-normal">(comma-separate multiple emails)</span></label>
                  <input value={emailTo} onChange={(e) => setEmailTo(e.target.value)} placeholder="one@example.com, two@example.com"
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">CC <span className="text-gray-400 font-normal">(comma-separate multiple emails)</span></label>
                  <input value={emailCc} onChange={(e) => setEmailCc(e.target.value)} placeholder="cc1@example.com, cc2@example.com"
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">BCC <span className="text-gray-400 font-normal">(comma-separate multiple emails)</span></label>
                  <input value={emailBcc} onChange={(e) => setEmailBcc(e.target.value)} placeholder="bcc@example.com"
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Subject</label>
                  <input value={emailSubject} onChange={(e) => setEmailSubject(e.target.value)}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-600 mb-1">Message</label>
                  <textarea value={emailMessage} onChange={(e) => setEmailMessage(e.target.value)} rows={4}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" />
                </div>
                <p className="text-xs text-gray-400">PDF of the PO will be attached automatically.</p>
                <div className="flex gap-3 pt-1">
                  <button onClick={handleSendEmail} disabled={sendingEmail}
                    className="flex-1 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white text-sm font-medium py-2 rounded-lg transition">
                    {sendingEmail ? 'Sending...' : 'Send with PDF'}
                  </button>
                  <button onClick={() => setEmailModal({ open: false, po: null })}
                    className="flex-1 border border-gray-200 text-gray-600 hover:bg-gray-50 text-sm font-medium py-2 rounded-lg transition">Cancel</button>
                </div>
              </div>
            ) : (
              <div className="p-4 max-h-72 overflow-y-auto">
                {historyLoading ? (
                  <div className="flex justify-center py-6">
                    <div className="animate-spin w-5 h-5 border-2 border-blue-600 border-t-transparent rounded-full" />
                  </div>
                ) : emailHistory.length === 0 ? (
                  <p className="text-sm text-gray-400 text-center py-6">No email history for this PO.</p>
                ) : (
                  <div className="space-y-2">
                    {emailHistory.map((log) => (
                      <div key={log._id} className="border border-gray-100 rounded-lg p-3">
                        <div className="flex items-center justify-between mb-1">
                          <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${log.status === 'sent' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>{log.status}</span>
                          <span className="text-xs text-gray-400">{format(new Date(log.createdAt), 'dd MMM yyyy, HH:mm')}</span>
                        </div>
                        <p className="text-xs text-gray-600 truncate">To: {log.to.join(', ')}</p>
                        <p className="text-xs text-gray-400 truncate">{log.subject}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
